services:
  mysql:
    image: mysql:8.4
    container_name: z-youtube-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zyoutube
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: